import Head from 'next/head'

export default function Films() {

	return (
		<div>
			<Head>
				<title>Filmes - Starwars</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>teste de filme</h1>
			</main>					
		</div>
	)	

}



