import Head from 'next/head';
import { styled } from '@mui/material/styles';
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';

const Item = styled(Paper)(({ theme }) => ({
	"background-color": '#FFF'
}));


export default function Films() {

	return (
		<div>
			<Head>
				<title>Filmes - Starwars</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
			<Container  maxWidth="sm">
				<Grid container spacing={2}>
				  <Grid item xs={8}>
				  	<Item><h3>teste</h3></Item>				    
				  </Grid>
				  <Grid item xs={4}>
				  	<Item><h3>teste</h3></Item>				    
				  </Grid>
				  <Grid item xs={4}>
				    <Item><h3>teste</h3></Item>
				  </Grid>
				  <Grid item xs={8}>
				    <Item><h3>teste</h3></Item>
				  </Grid>
				</Grid>			
			</Container>


			</main>					
		</div>
	)	

}



